trigger:
- main

pool:
  name: 'Default'

steps:
# Printing Sample Message
- script: echo "Hello Azure Pipelines User"
  displayName: "Hello Stage"

# Step 1: Fetch the Git Repository
- checkout: self
  displayName: "Fetching Git Repository"

# Debugging the OS of the Agent
- script: echo "Running on $(Agent.OS)"
  displayName: "Debug Agent OS"

# Step 2: Verify Repository Exists and List Files
- script: |
    if [ "$(Agent.OS)" == "Windows_NT" ]; then
      echo "Running On Windows"
      dir
    else 
      echo "Linux Agent detected. Listing files using ls -a: "
      ls -a
    fi

  displayName: Check Repo and List Files
  workingDirectory: $(System.DefaultWorkingDirectory)