# trigger:
#   - main

# pool:
#   name: 'default'

# steps:
#   - checkout: self

#   - script: echo $(Agent.OS)  # For Defining the OS pipeline is running
#     displayName: "Debug Agent OS"

#   - script: echo "Hello, Azure Pipelines"
#     displayName: "Hello Message"

#   - script: ls -l
#     displayName: "Listing Files from Linux"
#     condition: eq(variables['Agent.OS'], 'Linux')  # Listing files based on OS (linux)

#   - script: dir
#     displayName: "Listing Files from Windows"
#     condition: eq(variables['Agent.OS'], 'Windows_NT')  # Listing files based on OS (Windows)

#   - script: |



trigger:
- main

pool:
  name: 'Default'

steps:
- script: echo "Hello Azure Pipelines User"
  displayName: "Hello Stage"

- checkout: self
  displayName: "Checkout Code"

# Debugging the OS of the Agent
- script: echo "Running on $(Agent.OS)"
  displayName: "Debug Agent OS"

# Conditional Execution for Listing Files
- script: |
    if "%Agent.OS%" == "Windows_NT" (
      echo "Windows Agent detected. Listing files with dir:"
      dir
    ) else ( 
      echo "Linux Agent detected. Listing files with ls -a:"
      ls -a
  displayName: "Listing Files based on OS"
  condition: always()