trigger:
  - main

pool:
  name: 'default'

steps:
  - checkout: self

  - script: echo "Hello, Azure Pipelines"
    displayName: "Hello Message"

  - script: ls -l
    displayName: "List Files on Linux"
    condition: eq(variables['Agent.OS'], 'Linux')

  - script: dir
    displayName: "List Files on Windows"
    condition: eq(variables['Agent.OS'], 'Windows')
